---
deployment:
      tasks:
        - export DEPLOYPATH=/home/libuc6kfb0jg/Flytrap/Flytrap-Web/  # Add /<app_folder> if required
        - /bin/cp -r /home/libuc6kfb0jg/repositories/Flytrap/Flytrap-Web $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
