---
deployment:
      tasks:
        - export DEPLOYPATH=/home/libuc6kfb0jg/Flytrap/Flytrap-Web/  
        - /bin/cp -r /home/libuc6kfb0jg/repositories/Flytrap/ $DEPLOYPATH  # Copy all recursively to $DEPLOYPATH
        
