name: Bundle and minify scripts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: npm install
      run: npm install

    - name: Bundle browser scripts
      run: uglifyjs-folder scripts/client -o bundled/web.bundled.js

    - name: Bundle secure.js Node script and modules
      run: watchify scripts/node/secure.js -o bundled/secure.bundled.js

    - name: Bundle and minify all scripts into one file
      run: uglifyjs-folder bundled -o static/bundle.js
